package cricket.knowledgespike.scorer.ui.theme

import androidx.compose.ui.graphics.Color

val Seed = Color(0xFF136F63)

val PrimaryLight = Color(0xFF136F63)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFBCEFE3)
val OnPrimaryContainerLight = Color(0xFF003830)
val InversePrimaryLight = Color(0xFF7ADBC3)
val SecondaryLight = Color(0xFF1F5A8A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD2E4FF)
val OnSecondaryContainerLight = Color(0xFF003258)
val TertiaryLight = Color(0xFFA86F00)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFE6BE)
val OnTertiaryContainerLight = Color(0xFF362100)
val BackgroundLight = Color(0xFFF5F8F4)
val OnBackgroundLight = Color(0xFF151D1A)
val SurfaceLight = Color(0xFFF7FAF6)
val OnSurfaceLight = Color(0xFF151D1A)
val SurfaceVariantLight = Color(0xFFD9E5DF)
val OnSurfaceVariantLight = Color(0xFF3E4A45)
val SurfaceTintLight = Color(0xFF136F63)
val InverseSurfaceLight = Color(0xFF2A322F)
val InverseOnSurfaceLight = Color(0xFFECF2EE)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410E0B)
val OutlineLight = Color(0xFF6F7E77)
val OutlineVariantLight = Color(0xFFBECDC6)
val ScrimLight = Color(0xFF000000)
val SurfaceBrightLight = Color(0xFFF7FAF6)
val SurfaceContainerLight = Color(0xFFE9EFEA)
val SurfaceContainerHighLight = Color(0xFFE4EAE6)
val SurfaceContainerHighestLight = Color(0xFFDEE5E0)
val SurfaceContainerLowLight = Color(0xFFF1F5F1)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceDimLight = Color(0xFFD7DDD9)

val PrimaryDark = Color(0xFF7ADBC3)
val OnPrimaryDark = Color(0xFF00382F)
val PrimaryContainerDark = Color(0xFF005246)
val OnPrimaryContainerDark = Color(0xFFBCEFE3)
val InversePrimaryDark = Color(0xFF136F63)
val SecondaryDark = Color(0xFFA4CBF2)
val OnSecondaryDark = Color(0xFF003258)
val SecondaryContainerDark = Color(0xFF174A73)
val OnSecondaryContainerDark = Color(0xFFD2E4FF)
val TertiaryDark = Color(0xFFF2C15D)
val OnTertiaryDark = Color(0xFF4B3200)
val TertiaryContainerDark = Color(0xFF6C4A00)
val OnTertiaryContainerDark = Color(0xFFFFE6BE)
val BackgroundDark = Color(0xFF0E1512)
val OnBackgroundDark = Color(0xFFDCE5DF)
val SurfaceDark = Color(0xFF121B17)
val OnSurfaceDark = Color(0xFFDCE5DF)
val SurfaceVariantDark = Color(0xFF3E4A45)
val OnSurfaceVariantDark = Color(0xFFBDC9C3)
val SurfaceTintDark = Color(0xFF7ADBC3)
val InverseSurfaceDark = Color(0xFFDCE5DF)
val InverseOnSurfaceDark = Color(0xFF2A322F)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val OutlineDark = Color(0xFF86958E)
val OutlineVariantDark = Color(0xFF3E4A45)
val ScrimDark = Color(0xFF000000)
val SurfaceBrightDark = Color(0xFF343D39)
val SurfaceContainerDark = Color(0xFF1E2623)
val SurfaceContainerHighDark = Color(0xFF28302D)
val SurfaceContainerHighestDark = Color(0xFF333B37)
val SurfaceContainerLowDark = Color(0xFF171F1C)
val SurfaceContainerLowestDark = Color(0xFF0A100D)
val SurfaceDimDark = Color(0xFF121B17)

val PrimaryFixed = Color(0xFFBCEFE3)
val PrimaryFixedDim = Color(0xFF7ADBC3)
val OnPrimaryFixed = Color(0xFF002019)
val OnPrimaryFixedVariant = Color(0xFF005246)
val SecondaryFixed = Color(0xFFD2E4FF)
val SecondaryFixedDim = Color(0xFFA4CBF2)
val OnSecondaryFixed = Color(0xFF001D33)
val OnSecondaryFixedVariant = Color(0xFF174A73)
val TertiaryFixed = Color(0xFFFFE6BE)
val TertiaryFixedDim = Color(0xFFF2C15D)
val OnTertiaryFixed = Color(0xFF2A1800)
val OnTertiaryFixedVariant = Color(0xFF6C4A00)


